trigger:
- main

pool: my-personal-computer

steps:

  
- task: vercel-deployment-task@1

  inputs:
    vercelProjectId: 'prj_XCNtMLuYSI9YMGOA7C2nmEuHpO9c' 
    vercelOrgId: 'a6XwkJZUGLpLiIIbPBsulKBQ' 
    vercelToken: $(VERCEL_TOKEN)
    production: true



