trigger:
- main

pool: my-personal-computer

steps:
- task: vercel-deployment-task@1

  inputs:
    vercelProjectId: 'prj_GACqPalMK3irgD1j6lzDKYRS7PPf' 
    vercelOrgId: 'a6XwkJZUGLpLiIIbPBsulKBQ' 
    vercelToken: $(VERCEL_TOKEN)
    production: true

