trigger:
- main

pool: my-personal-computer

steps:

- task: vercel-deployment-task@1

  inputs:
    vercelProjectId: 'prj_8jWqf6VBAm50Msp96oKfkCuuU4z0' 
    vercelOrgId: 'a6XwkJZUGLpLiIIbPBsulKBQ' 
    vercelToken: $(VERCEL_TOKEN)
    production: true
