trigger:
- main

pool: my-personal-computer

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: vercel-deployment-task@1
  inputs:
    vercelProjectId: 'prj_GACqPalMK3irgD1j6lzDKYRS7PPf' 
    vercelOrgId: 'a6XwkJZUGLpLiIIbPBsulKBQ' 
    vercelToken: $(vercelToken)
    production: true

